services:
  java-context-service:
    image: java-class-context:latest
    ports:
      - "8080:8080"
    volumes:
      - artifacts-data:/app/artifacts
    environment:
      APP_PARSE_CACHE_ENABLED: "true"
      APP_PARSE_CACHE_DIR: /app/artifacts
      APP_ARTIFACTS_DIR: /app/artifacts
      LOGGING_LEVEL_SERVICE_STRUCTURE: INFO
    restart: unless-stopped

volumes:
  artifacts-data: