spring.application.name=java-class-context

# Swagger UI: http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs

# Отключить дефолтный редирект /swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true

# Сортировка методов в UI
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
